config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  get 'searchMAT', to: 'materiels#search'
  resources :adherents
  get '/searchADH', to: 'adherents#search'
  get '/export', to: 'adherents#export'
  resources :auteurs do
    resources :documents
  end
  get '/searchAUT', to: 'auteurs#search'
  namespace :auteur do
    resources :documents
  end
  devise_for :users
  root to: "static_pages#index"
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :auteur

  # validates :status, inclusion: { in: ['','',''] }
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auteur
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET auteurs/1/documents
  def index
    @documents = @auteur.documents
  end

  # GET auteurs/1/documents/1
  def show
  end

  # GET auteurs/1/documents/new
  def new
    @document = @auteur.documents.build
  end

  # GET auteurs/1/documents/1/edit
  def edit
  end

  # POST auteurs/1/documents
  def create
    @document = @auteur.documents.build(document_params)

    if @document.save
      redirect_to(@document.auteur)
    else
      render action: 'new'
    end
  end

  # PUT auteurs/1/documents/1
  def update
    if @document.update_attributes(document_params)
      redirect_to(@document.auteur)
    else
      render action: 'edit'
    end
  end

  # DELETE auteurs/1/documents/1
  def destroy
    @document.destroy

    redirect_to @auteur
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auteur
      @auteur = Auteur.find(params[:auteur_id])
    end

    def set_document
      @document = @auteur.documents.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def document_params
      params.require(:document).permit(:titre, :auteur_id)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: [@document.auteur, @document]) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br />
    <%= f.text_field :titre , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :auteur %><br />
    <%= f.text_field :auteur , class: 'form-control' , disabled: true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', [@document.auteur, @document] %> |
<%= link_to 'Back', auteur_documents_path(@document.auteur) %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table class="table">
  <tr>
    <th>Titre</th>
    <th>Auteur</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.titre %></td>
    <td><%= document.auteur %></td>
    <td><button class="btn btn-success btn-sm"><%= link_to 'Show', [document.auteur, document] %></td>
    <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', [document.auteur, document], method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
  </tr>
<% end %>
</table>

<br />

<button class="btn btn-primary"><%= link_to 'New Document', new_auteur_document_path(params[:auteur_id]) %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', @document.auteur %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titre:</b>
  <%= @document.titre %>
</p>

<p>
  <b>Auteur:</b>
  <%= @document.auteur.nom %>
</p>

<%= link_to 'Back', @document.auteur %>