config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  get 'searchMAT', to: 'materiels#search'
  resources :adherents
  get '/searchADH', to: 'adherents#search'
  get '/export', to: 'adherents#export'
  resources :auteurs do
    resources :documents
  end
  get '/searchAUT', to: 'auteurs#search'
  namespace :auteur do
    resources :documents
  end
  devise_for :users
  root to: "static_pages#index"
end

app/models/adherent.rb
class Adherent < ApplicationRecord
    validates :status, inclusion: { in: ['ENSEIGNANT','ETUDIANT'] }

    STATUS_OPTIONS = [
        ['ENSEIGNANT'],
        ['ETUDIANT']
    ]
    def to_s
        "ID : #{self.id} - Nom : "+self.nom+" - Prenom : "+self.prenom+" - Statut : "+self.status
    end
end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_adherent, only: %i[ show edit update destroy ]

  # GET /adherents or /adherents.json
  def index
    @adherents = Adherent.all
  end

  def export
    myarray = Adherent.all
    CSV.open("C:\\Users\\LENOVO\\Desktop\\semestre8\\Ruby On Rails\\cours\\Test Ruby on Rails\\LibraryManagement\\public\\sortie.csv", "w") do |f|
           myarray.each do |x|
                f << [x]
              end
        end
  end

  def search
    @adherents = Adherent.where("nom LIKE ?","%"+params[:q]+"%")
  end

  # GET /adherents/1 or /adherents/1.json
  def show
  end

  # GET /adherents/new
  def new
    @adherent = Adherent.new
  end

  # GET /adherents/1/edit
  def edit
  end

  # POST /adherents or /adherents.json
  def create
    @adherent = Adherent.new(adherent_params)

    respond_to do |format|
      if @adherent.save
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully created." }
        format.json { render :show, status: :created, location: @adherent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adherents/1 or /adherents/1.json
  def update
    respond_to do |format|
      if @adherent.update(adherent_params)
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully updated." }
        format.json { render :show, status: :ok, location: @adherent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adherents/1 or /adherents/1.json
  def destroy
    @adherent.destroy

    respond_to do |format|
      format.html { redirect_to adherents_url, notice: "Adherent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adherent
      @adherent = Adherent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adherent_params
      params.require(:adherent).permit(:nom, :prenom, :status)
    end
end

app/helpers/adherents_helper.rb
module AdherentsHelper
end

app/views/adherents/_form.html.erb
<%= form_with(model: adherent) do |form| %>
  <% if adherent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adherent.errors.count, "error") %> prohibited this adherent from being saved:</h2>

      <ul>
        <% adherent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom , class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :prenom %>
    <%= form.text_field :prenom ,class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status ,Adherent::STATUS_OPTIONS %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adherents/edit.html.erb
<h1>Editing Adherent</h1>

<%= render 'form', adherent: @adherent %>

<%= link_to 'Show', @adherent %> |
<%= link_to 'Back', adherents_path %>

app/views/adherents/export.html.erb
<p id="notice"><%= notice %></p>

<h1>Adherents</h1>
<p>Tout les adherents sont exporter dans un fichier csv </p>
<p>Path "C:\Users\LENOVO\Desktop\semestre8\Ruby On Rails\cours\Test Ruby on Rails\LibraryManagement\public\sortie.csv"</p>
<button class="btn btn-sm btn-primary"><a href="adherents">back</a></button>
<br>

app/views/adherents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adherents</h1>
<form action="/searchADH">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">CHERCHER L'ADHERENT</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LE NOM DE L'ADHERENT">
</div>
</form>
<form action="/export">
  <button class="btn btn-sm btn-success" type="submit" id="button-addon1">EXPORT TO CSV</button>
</form>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adherents.each do |adherent| %>
      <tr>
        <td><%= adherent.nom %></td>
        <td><%= adherent.prenom %></td>
        <td><%= adherent.status %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', adherent %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_adherent_path(adherent) %></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', adherent, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-primary"><%= link_to 'New Adherent', new_adherent_path %></button>

app/views/adherents/new.html.erb
<h1>New Adherent</h1>

<%= render 'form', adherent: @adherent %>

<%= link_to 'Back', adherents_path %>

app/views/adherents/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Adherents</h1>
<form action="/searchADH">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">SEARCH</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LE NOM DE L'ADHERENT">
</div>
</form>
<form action="/export">
  <button class="btn btn-sm btn-success" type="submit" id="button-addon1">EXPORT TO CSV</button>
</form>
<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adherents.each do |adherent| %>
      <tr>
        <td><%= adherent.nom %></td>
        <td><%= adherent.prenom %></td>
        <td><%= adherent.status %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', adherent %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_adherent_path(adherent) %></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', adherent, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adherent', new_adherent_path %>

app/views/adherents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @adherent.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @adherent.prenom %>
</p>

<p>
  <strong>Status:</strong>
  <%= @adherent.status %>
</p>

<%= link_to 'Edit', edit_adherent_path(@adherent) %> |
<%= link_to 'Back', adherents_path %>