config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  get 'searchMAT', to: 'materiels#search'
  resources :adherents
  get '/searchADH', to: 'adherents#search'
  get '/export', to: 'adherents#export'
  resources :auteurs do
    resources :documents
  end
  get '/searchAUT', to: 'auteurs#search'
  namespace :auteur do
    resources :documents
  end
  devise_for :users
  root to: "static_pages#index"
end

app/models/materiel.rb
class Materiel < ApplicationRecord
    validates :os, inclusion: { in: ['WINDOWS','MAC OS','UBUNTU','DEBIAN'] }

    OS_OPTIONS = [
        ['WINDOWS'],
        ['MAC OS'],
        ['UBUNTU'],
        ['DEBIAN']
    ]
end

app/controllers/materiels_controller.rb
class MaterielsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_materiel, only: %i[ show edit update destroy ]

  # GET /materiels or /materiels.json
  def index
    @materiels = Materiel.all
  end

  # GET /materiels/1 or /materiels/1.json
  def show
  end

  def search
    @materiels = Materiel.where("marque LIKE ?","%"+params[:q]+"%")
  end

  # GET /materiels/new
  def new
    @materiel = Materiel.new
  end

  # GET /materiels/1/edit
  def edit
  end

  # POST /materiels or /materiels.json
  def create
    @materiel = Materiel.new(materiel_params)

    respond_to do |format|
      if @materiel.save
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully created." }
        format.json { render :show, status: :created, location: @materiel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materiels/1 or /materiels/1.json
  def update
    respond_to do |format|
      if @materiel.update(materiel_params)
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully updated." }
        format.json { render :show, status: :ok, location: @materiel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiels/1 or /materiels/1.json
  def destroy
    @materiel.destroy

    respond_to do |format|
      format.html { redirect_to materiels_url, notice: "Materiel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materiel
      @materiel = Materiel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materiel_params
      params.require(:materiel).permit(:marque, :os)
    end
end

app/helpers/materiels_helper.rb
module MaterielsHelper
end

app/views/materiels/_form.html.erb
<%= form_with(model: materiel) do |form| %>
  <% if materiel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(materiel.errors.count, "error") %> prohibited this materiel from being saved:</h2>

      <ul>
        <% materiel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marque %>
    <%= form.text_field :marque,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :os %>
    <%= form.select :os,Materiel::OS_OPTIONS %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materiels/edit.html.erb
<h1>Editing Materiel</h1>

<%= render 'form', materiel: @materiel %>

<%= link_to 'Show', @materiel %> |
<%= link_to 'Back', materiels_path %>

app/views/materiels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materiels</h1>
<form action="/searchMAT">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">CHERCHER LE MATERIEL</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LA MARQUE DU MATERIEL">
</div>
</form>

<table class="table">
  <thead>
    <tr>
      <th>Marque</th>
      <th>Os</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materiels.each do |materiel| %>
      <tr>
        <td><%= materiel.marque %></td>
        <td><%= materiel.os %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', materiel %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_materiel_path(materiel) %></button></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', materiel, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-primary"><%= link_to 'New Materiel', new_materiel_path %>

app/views/materiels/new.html.erb
<h1>New Materiel</h1>

<%= render 'form', materiel: @materiel %>

<%= link_to 'Back', materiels_path %>

app/views/materiels/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Materiels</h1>
<form action="/searchMAT">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">CHERCHER LE MATERIEL</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LA MARQUE DU MATERIEL">
</div>
</form>

<table class="table">
  <thead>
    <tr>
      <th>Marque</th>
      <th>Os</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materiels.each do |materiel| %>
      <tr>
        <td><%= materiel.marque %></td>
        <td><%= materiel.os %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', materiel %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_materiel_path(materiel) %></button></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', materiel, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Materiel', new_materiel_path %>

app/views/materiels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marque:</strong>
  <%= @materiel.marque %>
</p>

<p>
  <strong>Os:</strong>
  <%= @materiel.os %>
</p>

<%= link_to 'Edit', edit_materiel_path(@materiel) %> |
<%= link_to 'Back', materiels_path %>