config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  get 'searchMAT', to: 'materiels#search'
  resources :adherents
  get '/searchADH', to: 'adherents#search'
  get '/export', to: 'adherents#export'
  resources :auteurs do
    resources :documents
  end
  get '/searchAUT', to: 'auteurs#search'
  namespace :auteur do
    resources :documents
  end
  devise_for :users
  root to: "static_pages#index"
end

app/models/auteur.rb
class Auteur < ApplicationRecord
  has_many :documents
end

app/controllers/auteurs_controller.rb
class AuteursController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auteur, only: %i[ show edit update destroy ]

  # GET /auteurs or /auteurs.json
  def index
    @auteurs = Auteur.all
  end

  def search
    @auteurs = Auteur.where("nom LIKE ?","%"+params[:q]+"%")
  end

  # GET /auteurs/1 or /auteurs/1.json
  def show
    @document=@auteur.documents.build
  end

  # GET /auteurs/new
  def new
    @auteur = Auteur.new
  end

  # GET /auteurs/1/edit
  def edit
  end

  # POST /auteurs or /auteurs.json
  def create
    @auteur = Auteur.new(auteur_params)

    respond_to do |format|
      if @auteur.save
        format.html { redirect_to auteur_url(@auteur), notice: "Auteur was successfully created." }
        format.json { render :show, status: :created, location: @auteur }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auteurs/1 or /auteurs/1.json
  def update
    respond_to do |format|
      if @auteur.update(auteur_params)
        format.html { redirect_to auteur_url(@auteur), notice: "Auteur was successfully updated." }
        format.json { render :show, status: :ok, location: @auteur }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auteurs/1 or /auteurs/1.json
  def destroy
    @auteur.destroy

    respond_to do |format|
      format.html { redirect_to auteurs_url, notice: "Auteur was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auteur
      @auteur = Auteur.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auteur_params
      params.require(:auteur).permit(:nom, :prenom)
    end
end

app/helpers/auteurs_helper.rb
module AuteursHelper
end

app/views/auteurs/_form.html.erb
<%= form_with(model: auteur) do |form| %>
  <% if auteur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auteur.errors.count, "error") %> prohibited this auteur from being saved:</h2>

      <ul>
        <% auteur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom,class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :prenom %>
    <%= form.text_field :prenom,class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/auteurs/edit.html.erb
<h1>Editing Auteur</h1>

<%= render 'form', auteur: @auteur %>

<%= link_to 'Show', @auteur %> |
<%= link_to 'Back', auteurs_path %>

app/views/auteurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auteurs</h1>
<form action="/searchAUT">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">CHERCHER L'AUTEUR</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LA NOM DE L'AUTEUR">
</div>
</form>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auteurs.each do |auteur| %>
      <tr>
        <td><%= auteur.nom %></td>
        <td><%= auteur.prenom %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', auteur %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_auteur_path(auteur) %></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', auteur, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn-primary"><%= link_to 'New Auteur', new_auteur_path %>

app/views/auteurs/new.html.erb
<h1>New Auteur</h1>

<%= render 'form', auteur: @auteur %>

<%= link_to 'Back', auteurs_path %>

app/views/auteurs/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Auteurs</h1>
<form action="/searchAUT">
<div class="input-group mb-3">
  <button class="btn btn-warning" type="submit" id="button-addon1">SEARCH</button>
  <input type="text" name="q" class="form-control" placeholder="ENTRER LA NOM DE L'AUTEUR">
</div>
</form>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auteurs.each do |auteur| %>
      <tr>
        <td><%= auteur.nom %></td>
        <td><%= auteur.prenom %></td>
        <td><button class="btn btn-dark btn-sm"><%= link_to 'Show', auteur %></td>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Edit', edit_auteur_path(auteur) %></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', auteur, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auteur', new_auteur_path %>

app/views/auteurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @auteur.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @auteur.prenom %>
</p>

<%= link_to 'Edit', edit_auteur_path(@auteur) %> |
<%= link_to 'Back', auteurs_path %>

<hr>

<h1>New document</h1>

<%= render 'documents/form' %>


<hr>

<h1>Listing documents</h1>

<table class="table">
  <tr>
    <th>Titre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @auteur.documents.each do |document| %>
<% if document.persisted? %>
  <tr>
    <td><%= document.titre %></td>
    <td><button class="btn btn-primary btn-sm"><%= link_to 'Show', [document.auteur, document] %></td>
    <td><button class="btn btn-primary btn-sm"><%= link_to 'Destroy', [document.auteur, document], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />